apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-policy-deployment
  labels:
    app: insurance-policy
spec:
  replicas:4 
  selector:
    matchLabels:
      app: insurance-policy
  template:
    metadata:
      labels:
        app: insurance-policy
    spec:
      containers:
        - name: insurance-policy-container
          image: akhilsru3/insure-me:3.0 
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
---
apiVersion: v1
kind: Service
metadata:
  name: insurance-policy-service
spec:
  type: NodePort
  selector:
    app: insurance-policy
  ports:
    - protocol: TCP
      port: 8080           
      targetPort: 8080     
      nodePort: 30080     
